language: minimal

services:
  - docker

script:
  - docker pull morfin/myalpine
  - docker run --name foosball -d -ti morfin/myalpine /bin/bash
  - docker cp CMakeLists.txt foosball:/src/CMakeLists.txt
  - docker cp _clang-format foosball:/src/_clang-format
  - docker cp cmake foosball:src/cmake
  - docker cp config_example.json foosball:/src/configuration.json
  - docker cp data foosball:/src/data
  - docker cp demo foosball:/src/demo
  - docker cp fastbuild.cmake foosball:/src/fastbuild.cmake
  - docker cp include foosball:/src/include
  - docker cp src foosball:/src/src
  - docker cp test foosball:/src/test
  - docker exec -ti foosball /bin/bash -c "mkdir release debug"
  - docker exec -ti foosball /bin/bash -c "cd release; cmake -DCMAKE_BUILD_TYPE=Release ..; cmake --build . --config Release;"
  - docker exec -ti foosball /bin/bash -c "cd debug; cmake -DCMAKE_BUILD_TYPE=Debug ..; cmake --build . --config Debug;"